### ISSUE TITLE
Certid = null when a certification is created

### ISSUE THREAD

**Issue by a-coutarel** [atlet/moodle-local_badgecerts#11]
Hi guys,

I had a problem when I wanted to create a certification. When I selected a moodle badge, its id was not saved as a certid in the database (certid=null). But if I create a certification and then edit it to select my moodle badge, it works (certid=moodle badge id in database).

To solve the problem, I just put the following line in new.php:
$fordb->certid = $data->certid;

Thank you for your work !

**Comment by atlet** [comment]
Tnx for fix.
