### ISSUE TITLE
PHP Warning when creating new certtificate

### ISSUE THREAD

**Issue by mudrd8mz** [atlet/moodle-local_badgecerts#2]
Warning: Creating default object from empty value in ./local/badgecerts/new.php on line 96

**Comment by atlet** [comment]
Can you help me produce this warning? I don't see it. What did you entered in fields. Tnx.

**Comment by atlet** [comment]
Just checking, which version of plugin did you installed?

**Comment by mudrd8mz** [comment]
We always evaluate the latest version available as a ZIP in the plugins directory.
