### ISSUE TITLE
Unable to preview the ceritifcate due to PHP notices and warnings

### ISSUE THREAD

**Issue by mudrd8mz** [atlet/moodle-local_badgecerts#3]
![image](https://user-images.githubusercontent.com/85831/88288186-b1c7c500-ccf3-11ea-832e-4e3bfeeda443.png)

**Comment by atlet** [comment]
Can you send me the svg template you used. Tnx.

**Comment by mudrd8mz** [comment]
Hardly, it's a few months now.

**Comment by atlet** [comment]
Can be, that was selected a wrong file - non svg.
