### ISSUE TITLE
SQL expects the mod_booking module present

### ISSUE THREAD

**Issue by mudrd8mz** [atlet/moodle-local_badgecerts#6]
I noticed certain SQL queries accessing the tables like `booking_answers` or `booking_options` that may not be present. There is no dependency on the other module declared. So is the Booking module needed?

https://docs.moodle.org/dev/Plugin_contribution_checklist#Dependencies

**Comment by atlet** [comment]
No, it's not needed. It check if it's installed. If it's not, then this SQL is excluded.
